title = "Pedro Pardal"
baseURL = "http://www.ppardalj.com/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-150818815-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Soy consultor, formador y desarrollador de software."
  facebook = ""
  twitter = "https://twitter.com/ppardalj"
  instagram = ""
  youtube = ""
  github = "https://github.com/ppardalj"
  gitlab = ""
  linkedin = "https://es.linkedin.com/in/pedro-pardal-jimena-36764344"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/zan-yBEUD8SWABc-unsplash.jpg"
  recent_posts_number = 2
