title: "Pedro Pardal"
baseURL: "https://www.ppardalj.com/"
languageCode: "en-us"
theme: "ananke"

MetaDataFormat: "yaml"
DefaultContentLanguage: "es"
SectionPagesMenu: "main"
Paginate: 3
googleAnalytics: "UA-150818815-1"
enableRobotsTXT: true
disqusShortname: "ppardalj"

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  description: "Soy consultor, formador y desarrollador de software."
  linkedin: "https://www.linkedin.com/in/ppardalj/"
  instagram: "https://www.instagram.com/ppardalj/"
  youtube: "https://www.youtube.com/@ppardalj"
  background_color_class: "bg-black"
  recent_posts_number: 2
