title: Pedro Pardal
theme: ppardalj
baseURL: https://www.ppardalj.com
languageCode: es-es
defaultContentLanguage: es
languages:
  es:
    weight: 1
  en:
    weight: 2
metaDataFormat: yaml
params:
  gtm_id: "GTM-TQGN65PV"
  facebookPixelId: 417415780749470
  facebookDomainVerification: xwbugjbpmp2jwy1y6mzdhe6ga267uz
  hotjarId: 5031744
  hubspotId: 8231847
markup:
  goldmark:
    renderer:
      unsafe: true
