title: Pedro Pardal
theme: ppardalj
baseURL: https://www.ppardalj.com
languageCode: es-es
defaultContentLanguage: es
languages:
  es:
    weight: 1
  en:
    weight: 2
metaDataFormat: yaml
params:
  gtm_id: "GTM-PJM6WP"
  hubspotId: 8231847
markup:
  goldmark:
    renderer:
      unsafe: true
